name: Release on all tags

on:
  push:
    tags:
      - "*"

jobs:
  release-non-mac:
    name: create release and publish brew formula
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go 1.18
        uses: actions/setup-go@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          args: release --rm-dist -f ./.goreleaser-non-mac.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
