name: Release on all tags

on:
  push:
    tags:
      - "*"

jobs:
  release-non-mac:
    permissions: write-all
    name: create release and publish brew formula
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go 1.18
        uses: actions/setup-go@v2

      - name: change go mod version
        run: |
          go mod edit -go 1.18

      - name: Run GoReleaser for non mac
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
